-- KNHS DocumentTrack V5 suggested Supabase schema
create table if not exists documents (
  id bigint generated by default as identity primary key,
  control_no text unique not null,
  reference_no text,
  subject text not null,
  document_type text,
  sender text,
  originating_office text,
  date_received date,
  due_date date,
  priority text default 'Normal',
  status text default 'Received',
  current_office text,
  current_custodian text,
  remarks text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists document_movements (
  id bigint generated by default as identity primary key,
  document_id bigint references documents(id) on delete cascade,
  route_from text,
  route_to text,
  received_by text,
  action text,
  status text,
  remarks text,
  created_at timestamptz default now()
);

-- Enable Row Level Security and create appropriate policies before production use.
